# Generated by Django 4.1.7 on 2023-05-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_collection_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vulnerabilites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("recommendation", models.TextField()),
                ("severity", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="ScanResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                (
                    "vulnerability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.vulnerabilites",
                    ),
                ),
            ],
        ),
    ]
