# Generated by Django 4.1.7 on 2023-05-13 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_vulnerabilites_scanresults"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ScanResults",
            new_name="ScanResult",
        ),
        migrations.RenameModel(
            old_name="Vulnerabilites",
            new_name="Vulnerability",
        ),
    ]
