# Generated by Django 4.1.7 on 2023-05-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_scan_scandetail_delete_scanresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="vulnerabilities",
            field=models.ManyToManyField(
                through="app.ScanDetail", to="app.vulnerability"
            ),
        ),
    ]
