# Generated by Django 4.1.7 on 2023-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_scandetail_user_scan_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="scan_type",
            field=models.CharField(default="Quick", max_length=150),
            preserve_default=False,
        ),
    ]
