# Generated by Django 4.1.7 on 2023-05-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_scan_scan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="coll_title",
            field=models.CharField(default="openapiVam.json", max_length=255),
            preserve_default=False,
        ),
    ]
