# Generated by Django 4.1.7 on 2023-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_scan_coll_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
