# Generated by Django 4.1.7 on 2023-05-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_scan_finished"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scan",
            name="finished",
        ),
        migrations.AddField(
            model_name="scan",
            name="status",
            field=models.CharField(default="RUNNING", max_length=150),
        ),
    ]
