# Generated by Django 4.1.7 on 2023-05-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_remove_scan_finished_scan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="scandetail",
            name="issue",
            field=models.TextField(default="Issue"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scandetail",
            name="response",
            field=models.TextField(default="issue"),
            preserve_default=False,
        ),
    ]
