# Generated by Django 4.1.7 on 2023-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_scandetail_issue_alter_scandetail_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="url",
            field=models.CharField(default="http://localhost:5000/", max_length=255),
            preserve_default=False,
        ),
    ]
