# Generated by Django 4.1.7 on 2023-05-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_scan_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scan",
            name="url",
        ),
        migrations.AddField(
            model_name="scandetail",
            name="url",
            field=models.CharField(default="http://localhost:5000/", max_length=255),
            preserve_default=False,
        ),
    ]
